config/routes.rb
ImageCrop::Application.routes.draw do

  root :to => 'project_assets#new'
  resources :project_assets do
    collection do
      get "crop"
      get "crop_update"
      post "crop_update"
    end
  end
  match '/assets/uploads/:model/:field/:fid/:handle' => 'gridfs#serve', handle: /.*/

end

app/models/project_asset.rb
class ProjectAsset
  include Mongoid::Document

  attr_accessor :crop_x, :crop_y, :crop_h, :crop_w
  #after_update :reprocess_profile, :if => :cropping?
  
  field :name
  
  mount_uploader :attachment, ProfileUploader

  def cropping?
    !crop_x.blank? and !crop_y.blank? and !crop_h.blank? and !crop_w.blank?
  end

  def profile_geometry
    db   = Mongo::Connection.new.db('image_crop_development')
    puts self.attachment.url(:large), "pathhhhhhhhhhhhhhhhhhhhhhhhh"
    img = MiniMagick::Image.read(Mongo::GridFileSystem.new(db).open(self.attachment.url(:large), 'r'))
    #img = MiniMagick::Image.open(@image)
    @geometry = {:width => img[:width], :height => img[:height] }
  end

  private

  def reprocess_profile
    #img = MiniMagick::Image.open(self.attachment.large.path)
    db   = Mongo::Connection.new.db('image_crop_development')

    img ||= MiniMagick::Image.read(Mongo::GridFileSystem.new(db).open(self.attachment.url(:large), 'r'))
    crop_params = "#{crop_w}x#{crop_h}+#{crop_x}+#{crop_y}"
    img.crop(crop_params)
    img.write("/home/raman/test.jpeg")
    attachment.recreate_versions!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gridfs_controller.rb
class GridfsController < ActionController::Metal
        def serve
                doc_id = params[:fid]
                puts "ffffffffffffffffffffffffffffffffffffffffff"
                begin
                        document = ProjectAsset.find(doc_id)

                        if document.nil? || document.attachment.nil?
                                raise Exception.new("Unable to find document with id #{doc_id}")
                        end

                        filename = Pathname.new(env['PATH_INFO']).basename.to_s
                        version = filename.include?('_') ? filename.split('_')[0] : nil

                        gridfs_file = document.attachment.file_version(version)
                        gridfs_file = document.attachment.file if gridfs_file.nil? || gridfs_file.length.nil?

                        self.headers['Content-Length'] = gridfs_file.content_length.to_s
                        self.headers['Expires'] = 1.year.from_now.httpdate
                        self.response_body = gridfs_file.read
                        self.content_type = gridfs_file.content_type
                rescue Exception => e
                        self.status = :file_not_found
                        self.content_type = 'text/plain'
                        self.response_body = e.message
                end
        end
end

app/controllers/project_assets_controller.rb
class ProjectAssetsController < ApplicationController

	def new
		@project_asset = ProjectAsset.new
	end

	def create
		@project_asset = ProjectAsset.new(params[:project_asset])
		if @project_asset.save
			redirect_to project_assets_url
		else
			render "new"
		end
	end

	def index
		@project_assets = ProjectAsset.all
	end

	def crop
    	@project_asset = ProjectAsset.find(params[:id])
  	end

  	def update
	    @project_asset = ProjectAsset.find(params[:id])
	    @project_asset.crop_x = params[:user]["crop_x"]
	    @project_asset.crop_y = params[:user]["crop_y"]
	    @project_asset.crop_h = params[:user]["crop_h"]
	    @project_asset.crop_w = params[:user]["crop_w"]
	    db   = Mongo::Connection.new.db('image_crop_development')
	    img ||= MiniMagick::Image.read(Mongo::GridFileSystem.new(db).open(@project_asset.attachment.url(:large), 'r'))
	    crop_params = "#{@project_asset.crop_w}x#{@project_asset.crop_h}+#{@project_asset.crop_x}+#{@project_asset.crop_y}"
	    img.crop(crop_params)
	    img.write("/home/raman/test.jpeg")
	    @project_asset.attachment.recreate_versions!
	    @project_asset.attachment = File.open '/home/raman/test.jpeg'
	    @project_asset.save
	    File.delete '/home/raman/test.jpeg'
	    redirect_to project_assets_url
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_assets_helper.rb
module ProjectAssetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageCrop</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/project_assets/_form.html.erb
<%= form_for @project_asset, :html => {:multipart => true} do |f| %>
  <% if @project_asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_asset.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @project_asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.file_field :attachment %>
  <div class="fields">
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_assets/crop.html.erb
<%= stylesheet_link_tag "jquery.Jcrop" %>
<%= javascript_include_tag "jquery.Jcrop.min" %>
<script type="text/javascript" charset="utf-8">
$(function() {
  $('#cropbox').Jcrop({
    onChange: update_crop,
    onSelect: update_crop,
    setSelect: [0, 0, 500, 500],
    aspectRatio: 1
  });
});

function update_crop(coords) {
    var rx = 100/coords.w;
    var ry = 100/coords.h;
    var lw = $('#cropbox').width();
    var lh = $('#cropbox').height();
    var ratio = <%= @project_asset.profile_geometry[:width] %> / lw ;
    
  $('#preview').css({
    width: Math.round(rx * lw) + 'px',
    height: Math.round(ry * lh) + 'px',
    marginLeft: '-' + Math.round(rx * coords.x) + 'px',
    marginTop: '-' + Math.round(ry * coords.y) + 'px'
  });
  $("#crop_x").val(Math.round(coords.x * ratio));
  $("#crop_y").val(Math.round(coords.y * ratio));
  $("#crop_w").val(Math.round(coords.w * ratio));
  $("#crop_h").val(Math.round(coords.h * ratio));
}
</script>

<%= image_tag @project_asset.attachment.url(:large), :id => "cropbox" %>

<h3>Preview</h3>
<div class="preview">
    <%= image_tag @project_asset.attachment.url(:large), :id => "preview" %>
</div>

<%= form_for @project_asset, :as => :user do |f| %>
    <% for attribute in [:crop_x, :crop_y, :crop_h, :crop_w] %>
        <%= f.hidden_field attribute, :id => attribute %>
    <% end %>
    <p><%= f.submit "Crop" %></p>
<% end %>

app/views/project_assets/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/project_assets/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Avatar</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project_assets.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= image_tag user.attachment.url(:thumb) %></td>
    <td><%#= link_to 'Show', user %></td>
    <td><%#= link_to 'Edit', edit_user_path(user) %></td>
    <td><%#= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
    <td><%= link_to 'Crop', crop_project_assets_path(:id => user.id) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_project_asset_path %>

app/views/project_assets/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/project_assets/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>